### PR TITLE
dotnet-host: Create /usr/lib/dotnet/dotnet6 symlink

### PR DESCRIPTION
**Pull request by woky**
Also fix script in base-passwd\_data.

Depends on: https://github.com/canonical/chisel/pull/37

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
does it depend on https://github.com/canonical/chisel/pull/37?

Also note the duplicate with https://github.com/canonical/chisel-releases/pull/13

**Comment by woky** [comment]
It is but it now depends on https://github.com/canonical/chisel/pull/39.

**Review by cjdcordeiro — APPROVED** [review]
lgtm and seems to work.

**Comment by woky** [comment]
This is not needed anymore because the versioned directories are gone https://github.com/ubuntu-rocks/dotnet/pull/83

**Pull request closed without merging**
