### PR TITLE
feat: add libtiff6 to 24.04

### PR DESCRIPTION
**Pull request by dulmandakh**
# Proposed changes

This PR adds slices for libtiff6 and its dependencies.

### Forward porting
- 22.04 - https://github.com/canonical/chisel-releases/pull/254

## Testing
```bash
# Example:
#  chisel cut ... --root <path> libtiff6_libs
#  sudo chroot <path> <app>
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Comment by dulmandakh** [comment]
@rebornplusplus please suggest a solution here. libtiff6 is linked against **liblerc4** on all architectures, but s390. And on s390, there is no liblerc4 package. https://packages.ubuntu.com/noble/libtiff6

**Comment by cjdcordeiro** [comment]
> @rebornplusplus please suggest a solution here. libtiff6 is linked against **liblerc4** on all architectures, but s390. And on s390, there is no liblerc4 package. https://packages.ubuntu.com/noble/libtiff6

I'm afraid the only workaround we have for this today is to
 - have an explicit comment in the SDF stating such a case
 - explicitly install that dependency at `cut` time

**Review by cjdcordeiro — APPROVED** [review]
lgtm, thanks. looking for a 2nd approval

**Review by zhijie-yang — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
