### PR TITLE
Add slice definition for iputils-ping

### PR DESCRIPTION
**Pull request by ElgmiliAbdeljalil**
# Proposed changes

## Testing

```bash
# Example:
#  chisel cut ... --root <path> <pkg>_<proposed-slice>
#  sudo chroot <path> <app>
```

## Checklist

* [ ] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [ ] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
Thanks for the PR @ElgmiliAbdeljalil 

Could you please sign the CLA so the check passes?

**Comment by rebornplusplus** [comment]
TODO: The base branch needs to be changed. It's currently `main`.

Which release are you adding the changes for @ElgmiliAbdeljalil? 24.04?

**Comment by clay-lake** [comment]
Hi @ElgmiliAbdeljalil 

Thanks for the contribution. I wanted to check in and ask if you could sign the CLA?

**Comment by cjdcordeiro** [comment]
Thanks ;) 

In the meantime, I'm gonna close this since it has been opened against the wrong branch. So a new PR needs to be raised against the correct ubuntu release

**Pull request closed without merging**
