### PR TITLE
feat(20.04) add slice for crun and uidmap

### PR DESCRIPTION
**Pull request by endersonmaia**
# Proposed changes

This PR will add crun and uidmap slices to Ubuntu 20.04 release

### Forward porting

- https://github.com/canonical/chisel-releases/pull/222
- https://github.com/canonical/chisel-releases/pull/224
- https://github.com/canonical/chisel-releases/pull/225

## Testing

```bash
❯ chisel cut \
    --release ./ \
    --root rootfs/ \
    crun_bins uidmap_bins
2024/04/20 12:06:00 Processing ./ release...
2024/04/20 12:06:00 Selecting slices...
2024/04/20 12:06:00 Fetching ubuntu 20.04 focal suite details...
2024/04/20 12:06:02 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal main component...
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal universe component...
2024/04/20 12:06:02 Fetching ubuntu 20.04 focal-security suite details...
2024/04/20 12:06:02 Release date: Fri, 19 Apr 2024 13:05:25 UTC
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal-security main component...
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal-security universe component...
2024/04/20 12:06:02 Fetching ubuntu 20.04 focal-updates suite details...
2024/04/20 12:06:02 Release date: Sat, 20 Apr 2024 10:04:23 UTC
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal-updates main component...
2024/04/20 12:06:02 Fetching index for ubuntu 20.04 focal-updates universe component...
2024/04/20 12:06:02 Fetching pool/main/g/glibc/libc6_2.31-0ubuntu9.15_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/libc/libcap2/libcap2_2.32-1ubuntu0.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/libs/libseccomp/libseccomp2_2.5.1-1ubuntu1~20.04.2_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/libg/libgpg-error/libgpg-error0_1.37-1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/libg/libgcrypt20/libgcrypt20_1.8.5-5ubuntu1.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/l/lz4/liblz4-1_1.9.2-2ubuntu0.20.04.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/x/xz-utils/liblzma5_5.2.4-1ubuntu1.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/s/systemd/libsystemd0_245.4-4ubuntu3.23_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/y/yajl/libyajl2_2.1.0-3ubuntu0.20.04.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/universe/c/crun/crun_0.12.1+dfsg-1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/a/audit/libaudit-common_2.8.5-2ubuntu6_all.deb...
2024/04/20 12:06:02 Fetching pool/main/libc/libcap-ng/libcap-ng0_0.7.9-2.1build1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/a/audit/libaudit1_2.8.5-2ubuntu6_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/p/pcre2/libpcre2-8-0_10.34-7ubuntu0.1_amd64.deb...
2024/04/20 12:06:02 Fetching pool/main/libs/libselinux/libselinux1_3.0-1build2_amd64.deb...
2024/04/20 12:06:02 Fetching pool/universe/s/shadow/uidmap_4.8.1-1ubuntu5.20.04.5_amd64.deb...
2024/04/20 12:06:02 Extracting files from package "libc6"...
2024/04/20 12:06:04 Extracting files from package "libcap2"...
2024/04/20 12:06:04 Extracting files from package "libseccomp2"...
2024/04/20 12:06:04 Extracting files from package "libgpg-error0"...
2024/04/20 12:06:04 Extracting files from package "libgcrypt20"...
2024/04/20 12:06:04 Extracting files from package "liblz4-1"...
2024/04/20 12:06:04 Extracting files from package "liblzma5"...
2024/04/20 12:06:04 Extracting files from package "libsystemd0"...
2024/04/20 12:06:04 Extracting files from package "libyajl2"...
2024/04/20 12:06:04 Extracting files from package "crun"...
2024/04/20 12:06:04 Extracting files from package "libaudit-common"...
2024/04/20 12:06:04 Extracting files from package "libcap-ng0"...
2024/04/20 12:06:04 Extracting files from package "libaudit1"...
2024/04/20 12:06:05 Extracting files from package "libpcre2-8-0"...
2024/04/20 12:06:05 Extracting files from package "libselinux1"...
2024/04/20 12:06:05 Extracting files from package "uidmap"...
❯ sudo chroot ./rootfs /usr/bin/newuidmap
usage: newuidmap <pid> <uid> <loweruid> <count> [ <uid> <loweruid> <count> ] ... 
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by zhijie-yang — CHANGES_REQUESTED** [review]
Looks good. There are some issues regarding the linting (see workflow runs) to be fixed, and it is suggested to add the copyright files explicitly in the slice definitions.

**Review by zhijie-yang — CHANGES_REQUESTED** [review]
Please also add the copyright files for `libcap2` and `libzstd1`.

**Review by zhijie-yang — APPROVED** [review]
Looks good to me. Thanks!

**Review by linostar — APPROVED** [review]
LGTM, thanks!

**Review by cjdcordeiro — APPROVED** [review]
Also added the `crun` test here. LGTM. Thanks @endersonmaia

**Comment by cjdcordeiro** [comment]
P.S. couldn't find a proper case to test `uidmap`. I think other slices and utilities would be needed in order to create a testable user space for something like `newuidmap`.

@endersonmaia if you have a testable scenario I'd be take to take it in!

**Comment by endersonmaia** [comment]
@cjdcordeiro by head, I think you could install crun and uidmap and create a container from a bundle (busybox?) and try to run with an unprivileged user.

AFAIK, when running a container with crun using an unprivileged user, it will require uidmap to work.

I may give it a try later, no promises :sweat_smile:

**Comment by cjdcordeiro** [comment]
That would be really useful :) thanks

**Pull request merged**
