### PR TITLE
chore(22.04): add lint job

### PR DESCRIPTION
**Pull request by rebornplusplus**
This PR adds a "Lint" job to lint the slices and chisel.yaml. It also refactors the existing slice definition files and chisel.yaml for the lint checks to pass.

### CODE REVIEW

**Review by linostar — APPROVED** [review]
LGTM, thanks.

**Review by cjdcordeiro — COMMENTED** [review]
can u pls share the link to the PR or Issue that targets the validation fixes flagged in this PR?

**Review by cjdcordeiro — APPROVED** [review]

**Comment by rebornplusplus** [comment]
Yeah, it is indeed #176. I created ROCKS-1033 to track it internally. I will add the fixes for the failures today actually. It should not take long.

**Comment by rebornplusplus** [comment]
Okay, so I refactored the files for this release. The checks should now be okay. Please take a look.

Also note that I would like to rebase the commits, **not squash** since the commits have different purposes and I want to keep a good history. So I will rebase the commits after approvals.

**Review by cjdcordeiro — APPROVED** [review]
lgtm, thanks

**Comment by rebornplusplus** [comment]
I have rebased the commits. Please do not "Squash and merge" when merging this. @cjdcordeiro

**Review by linostar — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
