### PR TITLE
feat(24.04): add python3-pip slices

### PR DESCRIPTION
**Pull request by rebornplusplus**
This PR adds the `python3-pip` slices and it's dependencies.

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
(discussed offline - it would be nice to have python version-specific slices)

**Review by linostar — CHANGES_REQUESTED** [review]

**Review by linostar — APPROVED** [review]
LGTM

**Comment by rebornplusplus** [comment]
@cjdcordeiro please take another look when you are free. :)

**Review by linostar — APPROVED** [review]

**Comment by clay-lake** [comment]
As per chisel-releases PR extravaganza: We are going to create a python3 SDF which links to python3.12 in the case of 24.04, then include python3_minimal to the pip3_bins slice so it works out of the box.

**Review by linostar — CHANGES_REQUESTED** [review]
Once https://github.com/canonical/chisel-releases/pull/387 is merged, use `python3_standard` as a dependency instead of `python3.12-standard`.
Also remove `bins` slice from python3-pip and rename `bins3-12` slice to become `bins`.

**Comment by norrisjeremy** [comment]
When will this slice be merged?

**Comment by linostar** [comment]
This is no longer blocked since #387 got merged.

**Comment by rebornplusplus** [comment]
Thanks for the nudge @norrisjeremy. The PR is updated.

**Review by cjdcordeiro — APPROVED** [review]
LGTM thanks

**Comment by norrisjeremy** [comment]
Will this also be forward-ported into 24.10?

**Comment by norrisjeremy** [comment]
Is there a reason why there isn't a `python3-venv` slice?

**Comment by rebornplusplus** [comment]
> Is there a reason why there isn't a `python3-venv` slice?

I reckon it wasn't needed so far by anyone. Please feel free to raise a PR.

**Comment by rebornplusplus** [comment]
> Will this also be forward-ported into 24.10?

Raised #428.

**Pull request merged**
