### PR TITLE
feat(20.04): add slice for netbase

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
feat(20.04): add slice for netbase

## Related issues/PRs
#155

### Forward porting
45ae94a2661fe919f5598b1a26bbfa10b684c274

## Testing

```bash
$ chisel cut --release chisel-releases/ --root foo netbase_default-hosts netbase_default-networks
2024/02/29 10:33:33 Processing chisel-releases/ release...
2024/02/29 10:33:33 Selecting slices...
2024/02/29 10:33:33 Fetching ubuntu 20.04 focal suite details...
2024/02/29 10:33:34 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal main component...
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal universe component...
2024/02/29 10:33:34 Fetching ubuntu 20.04 focal-security suite details...
2024/02/29 10:33:34 Release date: Thu, 29 Feb 2024 15:57:57 UTC
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal-security main component...
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal-security universe component...
2024/02/29 10:33:34 Fetching ubuntu 20.04 focal-updates suite details...
2024/02/29 10:33:34 Release date: Thu, 29 Feb 2024 16:00:14 UTC
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal-updates main component...
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal-updates universe component...
2024/02/29 10:33:34 Fetching pool/main/n/netbase/netbase_6.1_all.deb...
2024/02/29 10:33:34 Extracting files from package "netbase"...
$ ls foo/etc
./  ../  ethertypes  hosts  networks  protocols  rpc  services
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by zhijie-yang — APPROVED** [review]
Looks good to me.

**Comment by norrisjeremy** [comment]
@cjdcordeiro @rebornplusplus What's the hold-up on getting this merged? It's been languishing for over a month.

**Review by linostar — COMMENTED** [review]
This is missing the copyright file. can you add it please?

**Comment by cjdcordeiro** [comment]
> This is missing the copyright file. can you add it please?

I just did that. If the CI passes, we should be good to go

**Review by cjdcordeiro — APPROVED** [review]
LGTM, ty

**Pull request merged**
