### PR TITLE
chore(20.04): add lint job

### PR DESCRIPTION
**Pull request by rebornplusplus**
# Proposed changes

This PR adds a "Lint" job to lint the slices and chisel.yaml.

### Forward porting

* #147

### CODE REVIEW

**Review by linostar — APPROVED** [review]
LGTM, thanks.

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
will wait for the same as in https://github.com/canonical/chisel-releases/pull/147#issuecomment-1980730198

**Review by cjdcordeiro — APPROVED** [review]
Quite a lot of them. Thanks. LGTM

**Review by linostar — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
