### PR TITLE
feat(22.04): bump format to v1

### PR DESCRIPTION
**Pull request by cjdcordeiro**
# Proposed changes
Same as https://github.com/canonical/chisel-releases/pull/194

### Forward porting

https://github.com/canonical/chisel-releases/pull/194
https://github.com/canonical/chisel-releases/pull/193

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by rebornplusplus — APPROVED** [review]
Looks good to me, thank you!

**Review by linostar — APPROVED** [review]
LGTM

**Comment by cjdcordeiro** [comment]
> @rebornplusplus the pkg coverage is failing: https://github.com/canonical/chisel-releases/actions/runs/8297308411/job/22710112677

fixed now

**Review by letFunny — APPROVED** [review]
Thanks!

**Comment by cjdcordeiro** [comment]
@rebornplusplus does it look good to you? (since this is the most used release, I just want to triple check)

**Review by rebornplusplus — APPROVED** [review]
Looks good to me. Chisel >= v0.9.0 should work well with this. Thanks!

**Pull request merged**
