### PR TITLE
ci(spread): support slice testing through Spread (focal)

### PR DESCRIPTION
**Pull request by cjdcordeiro**
# Proposed changes

This is a backport of https://github.com/canonical/chisel-releases/pull/281
## Related issues/PRs

#281 

## Testing

```bash
spread
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Comment by rebornplusplus** [comment]
This is probably missing the changes for `.github/ci.yaml`.

**Comment by cjdcordeiro** [comment]
> This is probably missing the changes for `.github/ci.yaml`.

y my bad. fixed now

**Review by rebornplusplus — APPROVED** [review]

**Review by linostar — APPROVED** [review]
Looks good.

On another note, are we going to add integration tests for existing major slices?

**Comment by cjdcordeiro** [comment]
> Looks good.
> 
> On another note, are we going to add integration tests for existing major slices?

Yes, it should be done gradually, maybe piggy backing on PRs that touch untested SDFs

**Pull request merged**
