### PR TITLE
feat(24.04): bump format to v1

### PR DESCRIPTION
**Pull request by cjdcordeiro**
# Proposed changes
Bumps the `format` to **v1**, in line with the announced schema changes in https://discourse.ubuntu.com/t/chisel-v0-9-0-is-out/41759.

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by rebornplusplus — APPROVED** [review]
Looks good to me, thanks!

**Comment by rebornplusplus** [comment]
Note that we are missing 20.04.

**Review by linostar — APPROVED** [review]
LGTM

**Review by letFunny — APPROVED** [review]
Thanks!

**Comment by cjdcordeiro** [comment]
The CI errors are related to ongoing changes in the 24.04 packages upstream, and not this change, so I'm gonna merge this anyway.

The 24.04 updates are coming in #214

**Pull request merged**
