### PR TITLE
feat(24.04): add libcrypto++8t64 slice

### LINKED ISSUE #241: [epic] Add libcrypto++8 slices to 24.04
```
  Depends: libc6
  Depends: libgcc-s1
  Depends: libstdc++6
```

### PR DESCRIPTION
**Pull request by endersonmaia**
# Proposed changes

Add libcrypto++8t64 to 24.04

## Related issues/PRs

/closes #241 

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Comment by endersonmaia** [comment]
I'm not sure how to provide testing instructions for a lib slice? 

Maybe provide an output for the `ldd` ? Any guidance is appreciated.

**Review by zhijie-yang — APPROVED** [review]
LGTM. Thanks.

**Review by rebornplusplus — APPROVED** [review]
Looks good to me, thank you!

**Review by zhijie-yang — APPROVED** [review]
LGTM.

**Review by cjdcordeiro — APPROVED** [review]

**Pull request merged**
