### PR TITLE
feat: migrate slices from 23.04 to 23.10

### PR DESCRIPTION
**Pull request by cjdcordeiro**
This PR brings onto 23.10 the core slices from 23.04.

The major differences are:
   - `libicu71` is renamed to `libicu72` in Mantic

### CODE REVIEW

**Comment by liushuyu** [comment]
I think this one probably needs a rebase after Node.js slices have been merged?

**Review by rebornplusplus — CHANGES_REQUESTED** [review]
These slices might have a few issues:
- aspnetcore-runtime-6.0_libs
- dotnet-host_bins
- dotnet-hostfxr-6.0_libs
- liblttng-ust-common1_libs
- libunwind-13_libs

Common errors in those slices:
```log
error: slice package "dotnet-host" missing from archive
error: slice package "liblttng-ust-common1" missing from archive
error: slice package "libunwind-13" missing from archive
```

I ran [this hacky script](https://github.com/rebornplusplus/rocks-toolbox/blob/chisel-tools/verify-slices) to test the slices automatically. I have attached the logs below. Please note that some failures are false positive because of Chisel's connection timed out issue.

Logs: https://pastebin.mozilla.org/bfcdif00

**Comment by cjdcordeiro** [comment]
> These slices might have a few issues:
> 
> * aspnetcore-runtime-6.0_libs
> * dotnet-host_bins
> * dotnet-hostfxr-6.0_libs
> * liblttng-ust-common1_libs
> * libunwind-13_libs
> 
> Common errors in those slices:
> 
> ```
> error: slice package "dotnet-host" missing from archive
> error: slice package "liblttng-ust-common1" missing from archive
> error: slice package "libunwind-13" missing from archive
> ```
> 
> I ran [this hacky script](https://github.com/rebornplusplus/rocks-toolbox/blob/chisel-tools/verify-slices) to test the slices automatically. I have attached the logs below. Please note that some failures are false positive because of Chisel's connection timed out issue.
> 
> Logs: https://pastebin.mozilla.org/bfcdif00

@rebornplusplus that's arch-specific. .NET only exists for amd64 and arm64.
likewise, `libunwind-13` doesn't exist for s390x and `liblttng-ust-common1` doesn't exist for i386

Since we can't pin `essentials` by arch, those packages won't work for said architectures.

**Comment by cjdcordeiro** [comment]
> I think this one probably needs a rebase after Node.js slices have been merged?

Yep. rebased `openssl`

**Review by rebornplusplus — APPROVED** [review]
LGTM.

**Pull request merged**
