### PR TITLE
feat(24.04): add slice for libc-bin

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
feat(24.04): add slice for libc-bin

## Related issues/PRs
#155

### Forward porting
d3c1f481ea560df01a89fa589a89d01e770ff5b8

## Testing

```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_nsswitch           
2024/02/29 10:16:37 Processing chisel-releases/ release...
2024/02/29 10:16:38 Selecting slices...
2024/02/29 10:16:38 Fetching ubuntu 24.04 noble suite details...
2024/02/29 10:16:38 Release date: Thu, 29 Feb 2024 15:03:37 UTC
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble main component...
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble universe component...
2024/02/29 10:16:38 Fetching ubuntu 24.04 noble-security suite details...
2024/02/29 10:16:38 Release date: Thu, 04 Jan 2024 18:43:12 UTC
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble-security main component...
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble-security universe component...
2024/02/29 10:16:38 Fetching ubuntu 24.04 noble-updates suite details...
2024/02/29 10:16:38 Release date: Thu, 04 Jan 2024 18:43:15 UTC
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble-updates main component...
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble-updates universe component...
2024/02/29 10:16:38 Fetching pool/main/g/glibc/libc-bin_2.39-0ubuntu2_amd64.deb...
2024/02/29 10:16:38 Extracting files from package "libc-bin"...
$ ls foo/etc/nsswitch.conf 
foo/etc/nsswitch.conf
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by rebornplusplus — APPROVED** [review]
The changes look good to me. Note that the CLA check is failing though @norrisjeremy.

**Comment by norrisjeremy** [comment]
Hi @rebornplusplus,

I filled out the CLA form and received an email stating that I have added back on Feb 29.
I'm not sure what else I can do?

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
FYI, I just resubmitted the CLA form again.

**Comment by norrisjeremy** [comment]
FYI, I've been invited to join the `CanonicalContributorAgreement` organization now.

**Comment by rebornplusplus** [comment]
Hey, it is working now. I re-triggered the tests.

**Review by cjdcordeiro — APPROVED** [review]
super! thanks

**Pull request merged**
