### PR TITLE
feat(24.04): add slice for gosu

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
feat(24.04): add slice for gosu

### Forward porting
#431

## Checklist
* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context
```shell
$ chisel cut --release chisel-releases/ --root foo gosu_bins
2024/12/12 07:19:49 Processing chisel-releases/ release...
2024/12/12 07:20:03 Selecting slices...
2024/12/12 07:20:03 Fetching ubuntu 24.04 noble suite details...
2024/12/12 07:20:04 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble main component...
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble universe component...
2024/12/12 07:20:04 Fetching ubuntu 24.04 noble-security suite details...
2024/12/12 07:20:04 Release date: Thu, 12 Dec 2024 10:46:25 UTC
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble-security main component...
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble-security universe component...
2024/12/12 07:20:04 Fetching ubuntu 24.04 noble-updates suite details...
2024/12/12 07:20:04 Release date: Thu, 12 Dec 2024 12:00:17 UTC
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble-updates main component...
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble-updates universe component...
2024/12/12 07:20:04 Fetching pool/universe/g/gosu/gosu_1.17-1ubuntu0.24.04.2_amd64.deb...
2024/12/12 07:20:04 Extracting files from package "gosu"...
$ mkdir -p foo/proc/self
$ ln -sf /usr/sbin/gosu foo/proc/self/exe
$ sudo chroot foo gosu -h
   eg: gosu tianon bash
       gosu nobody:root bash -c 'whoami && id'
       gosu 1000:1 id

gosu version: 1.17 (go1.22.2 on linux/amd64; gc)
gosu license: Apache-2.0 (full text at https://github.com/tianon/gosu)

```

### CODE REVIEW

**Review by linostar — APPROVED** [review]
LGTM, thank you for your contribution.

**Review by zhijie-yang — APPROVED** [review]
Looks good to me, thanks!

**Review by rebornplusplus — APPROVED** [review]
Looks good to me, thank you!

**Review by clay-lake — APPROVED** [review]
Looks good to me, thanks! (see also #431)

**Pull request merged**
