### PR TITLE
feat(24.04): add slice for busybox

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
feat(24.04): add slice for busybox

## Related issues/PRs
#155

### Forward porting
384bc69aa44cd12b84be9401a518d4e67a9adf85
7fc4a3ddc2394ac668284e73f578afbef0cba04e
76ac1e56bfebecaa6ba8b2ab4c59682be7c633f6
06c868bf8393c3f4256e2cedda3a557a0386e54d
8fac0570ad90275b9597dbf1d01bdf401d7574e5
29d8e6bcf6e93c5e2e16c4d60358e95b1232f2c0

## Testing

```bash
$ chisel cut --release chisel-releases/ --root foo busybox_bins base-files_base
2024/02/29 10:12:09 Processing chisel-releases/ release...
2024/02/29 10:12:09 Selecting slices...
2024/02/29 10:12:09 Fetching ubuntu 24.04 noble suite details...
2024/02/29 10:12:09 Release date: Thu, 29 Feb 2024 15:03:37 UTC
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble main component...
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble universe component...
2024/02/29 10:12:09 Fetching ubuntu 24.04 noble-security suite details...
2024/02/29 10:12:09 Release date: Thu, 04 Jan 2024 18:43:12 UTC
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble-security main component...
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble-security universe component...
2024/02/29 10:12:09 Fetching ubuntu 24.04 noble-updates suite details...
2024/02/29 10:12:09 Release date: Thu, 04 Jan 2024 18:43:15 UTC
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble-updates main component...
2024/02/29 10:12:09 Fetching index for ubuntu 24.04 noble-updates universe component...
2024/02/29 10:12:09 Fetching pool/main/b/base-files/base-files_13ubuntu7_amd64.deb...
2024/02/29 10:12:09 Fetching pool/main/g/glibc/libc6_2.39-0ubuntu2_amd64.deb...
2024/02/29 10:12:09 Fetching pool/universe/b/busybox/busybox_1.36.1-6ubuntu1_amd64.deb...
2024/02/29 10:12:09 Extracting files from package "base-files"...
2024/02/29 10:12:09 Extracting files from package "libc6"...
2024/02/29 10:12:09 Extracting files from package "busybox"...
$ sudo chroot foo /usr/bin/busybox echo test                                            
test
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Comment by norrisjeremy** [comment]
@cjdcordeiro @rebornplusplus Can this be merged soon?

**Review by rebornplusplus — APPROVED** [review]
LGTM.

**Review by zhijie-yang — APPROVED** [review]
Looks good to me.

**Comment by norrisjeremy** [comment]
@cjdcordeiro @rebornplusplus What's the hold-up on getting this merged? It's been languishing for over a month.

**Comment by linostar** [comment]
@norrisjeremy can you please sign the [CLA](https://ubuntu.com/legal/contributors/agreement) so we can merge your PR?

**Comment by linostar** [comment]
> @norrisjeremy can you please sign the [CLA](https://ubuntu.com/legal/contributors/agreement) so we can merge your PR?

Nevermind, you already signed it. Can you please recommit with your github account that signed the CLA so that the CLA check passes.

**Review by cjdcordeiro — APPROVED** [review]
LGTM, thanks

**Pull request merged**
