### PR TITLE
fix(20.04): add gcc-10-base slice and make essential for libgcc-s1 and libstdc++6 slices to ensure copyright file is included

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
fix(20.04): add gcc-10-base slice and make essential for libgcc-s1 and libstdc++6 slices to ensure copyright file is included

## Related issues/PRs
#156

## Testing

```bash
$ chisel cut --release chisel-releases/ --root foo libgcc-s1_libs libstdc++6_libs
2024/02/29 15:11:26 Processing chisel-releases/ release...
2024/02/29 15:11:26 Selecting slices...
2024/02/29 15:11:26 Fetching ubuntu 20.04 focal suite details...
2024/02/29 15:11:26 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/02/29 15:11:26 Fetching index for ubuntu 20.04 focal main component...
2024/02/29 15:11:26 Fetching index for ubuntu 20.04 focal universe component...
2024/02/29 15:11:27 Fetching ubuntu 20.04 focal-security suite details...
2024/02/29 15:11:27 Release date: Thu, 29 Feb 2024 20:49:09 UTC
2024/02/29 15:11:27 Fetching index for ubuntu 20.04 focal-security main component...
2024/02/29 15:11:27 Fetching index for ubuntu 20.04 focal-security universe component...
2024/02/29 15:11:27 Fetching ubuntu 20.04 focal-updates suite details...
2024/02/29 15:11:27 Release date: Thu, 29 Feb 2024 20:51:19 UTC
2024/02/29 15:11:27 Fetching index for ubuntu 20.04 focal-updates main component...
2024/02/29 15:11:28 Fetching index for ubuntu 20.04 focal-updates universe component...
2024/02/29 15:11:28 Fetching pool/main/g/gcc-10/gcc-10-base_10.5.0-1ubuntu1~20.04_amd64.deb...
2024/02/29 15:11:28 Fetching pool/main/g/glibc/libc6_2.31-0ubuntu9.14_amd64.deb...
2024/02/29 15:11:28 Fetching pool/main/g/gcc-10/libgcc-s1_10.5.0-1ubuntu1~20.04_amd64.deb...
2024/02/29 15:11:28 Fetching pool/main/g/gcc-10/libstdc++6_10.5.0-1ubuntu1~20.04_amd64.deb...
2024/02/29 15:11:29 Extracting files from package "gcc-10-base"...
2024/02/29 15:11:29 Extracting files from package "libc6"...
2024/02/29 15:11:31 Extracting files from package "libgcc-s1"...
2024/02/29 15:11:31 Extracting files from package "libstdc++6"...
$ find foo/usr/share/doc
foo/usr/share/doc
foo/usr/share/doc/libc6
foo/usr/share/doc/libc6/copyright
foo/usr/share/doc/libstdc++6
foo/usr/share/doc/gcc-10-base
foo/usr/share/doc/gcc-10-base/copyright
foo/usr/share/doc/libgcc-s1
$ readlink foo/usr/share/doc/libgcc-s1 foo/usr/share/doc/libstdc++6
gcc-10-base
gcc-10-base
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Comment by norrisjeremy** [comment]
@cjdcordeiro @rebornplusplus What's the hold-up on getting this merged? It's been languishing for over a month.

**Review by linostar — COMMENTED** [review]
@norrisjeremy Can you please fix the linting issue in gcc-12-base.yaml and commit using your github account that signed the CLA?

**Comment by norrisjeremy** [comment]
Closing this b/c noone seems interested in merging this.

**Comment by cjdcordeiro** [comment]
@norrisjeremy pls note that changes were requested and thus the PR could not be merged without them. We'll be happy to merge your PR if you address those changes.

**Comment by norrisjeremy** [comment]
@cjdcordeiro I'm uninterested in pursing this further. The suggested changes seem pointless and nitpicky.
Also, this project doesn't seem to be especially friendly to outside contributions, as evidenced by the extreme number of hoops that contributors are required to jump through & the large number of PRs that are left languishing & unmerged.

**Pull request closed without merging**
