### PR TITLE
[24.04] feat: Add libasan8

### PR DESCRIPTION
**Pull request by timo-reymann**
# Proposed changes

### Forward porting

Already for latest

## Testing

```bash
chisel cut --release local-chisel-releases/ --root myrootfs/ libasan8_libs
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context
This is basically the upgrade for https://github.com/canonical/chisel-releases/pull/56

### CODE REVIEW

**Comment by timo-reymann** [comment]
@cjdcordeiro i did sign the CLA, but it seems to be not recognized by the check 😅

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
Thanks for this @timo-reymann . Once the CLA is signed the and linting is fixed, this should be quite straightforward to merge ;)

**Comment by timo-reymann** [comment]
@cjdcordeiro lint is fixed, signed the CLA a few minutes ago tho - might be that it takes a while to sync or sth?

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
the PR needs a rebase

**Comment by timo-reymann** [comment]
No one from Canonical seems to feel responsible to answering any messages regarding signing the CLA. I will patch this locally, not contributing the change back.

I am frankly very disappointed about such a lacking signing process. It's frustrating to see that is made unnecessarily hard to contribute and not even respond to people willing to do so via mail / contact form.

I am closing this PR.

**Comment by cjdcordeiro** [comment]
I'm sorry for the lack of response Timo. I believe the team responsible for the CLA process has been having some issues with it and many other contributors were facing similar CI errors. 

I can already see you in the [cla list](https://cla-checker.canonical.com/check_user/timo-reymann), so if you want to re-open the PR, I'd be happy to merge it even if the CLA check fails.

**Pull request closed without merging**
