### PR TITLE
chore(22.04): Fix minor typo in "countries"

### PR DESCRIPTION
**Pull request by jbonnier**
# Proposed changes

This PR fixes a minor typo in the tzdata slice.

## Related issues/PRs
n/a

### Forward porting

It only fixes the typo for the two versions with the tzdata slices (22.04 and 23.04).

## Testing

n/a

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context
n/a

### CODE REVIEW

**Review by rebornplusplus — APPROVED** [review]
Thanks!

**Review by zhijie-yang — APPROVED** [review]
Looks good!

**Review by cjdcordeiro — APPROVED** [review]

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
@jbonnier did you sign the CLA? The check is failing, so if you have, we need to have a look at it

**Comment by jbonnier** [comment]
> @jbonnier did you sign the CLA? The check is failing, so if you have, we need to have a look at it

Yes, I did, however, I did it with a working email but I do my commits with a no-reply email. That may be why. Can I add an extra email address to the CLA?

**Comment by jbonnier** [comment]
@cjdcordeiro it should be good now, I added my noreply address to my launchpad account.

**Comment by cjdcordeiro** [comment]
@jbonnier thanks.

It is still failing though. Can you pls share your launchpad account?

**Comment by jbonnier** [comment]
@cjdcordeiro sure the username is `jubonnier` however the same PR has been merged for 23.04 🤔

**Comment by cjdcordeiro** [comment]
Is this correct: https://launchpad.net/~jubonnier ? It doesn't seem to exist

**Comment by jbonnier** [comment]
@cjdcordeiro https://launchpad.net/~jubonnier is my profile page

**Comment by cjdcordeiro** [comment]
I can see your LP profile now. The email is set as private though, but pls make sure the profile is associated with noreply (at) julienbonnier.com

**Pull request merged**
