### PR TITLE
feat(22.04): add slice for netbase

### PR DESCRIPTION
**Pull request by norrisjeremy**
# Proposed changes
feat(22.04): add slice for netbase

## Related issues/PRs
#155

### Forward porting
45ae94a2661fe919f5598b1a26bbfa10b684c274

## Testing

```bash
$ chisel cut --release chisel-releases/ --root foo netbase_default-hosts netbase_default-networks
2024/02/29 10:31:17 Processing chisel-releases/ release...
2024/02/29 10:31:18 Selecting slices...
2024/02/29 10:31:18 Fetching ubuntu 22.04 jammy suite details...
2024/02/29 10:31:18 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/02/29 10:31:18 Fetching index for ubuntu 22.04 jammy main component...
2024/02/29 10:31:18 Fetching index for ubuntu 22.04 jammy universe component...
2024/02/29 10:31:18 Fetching ubuntu 22.04 jammy-security suite details...
2024/02/29 10:31:19 Release date: Thu, 29 Feb 2024 15:55:42 UTC
2024/02/29 10:31:19 Fetching index for ubuntu 22.04 jammy-security main component...
2024/02/29 10:31:19 Fetching index for ubuntu 22.04 jammy-security universe component...
2024/02/29 10:31:19 Fetching ubuntu 22.04 jammy-updates suite details...
2024/02/29 10:31:19 Release date: Thu, 29 Feb 2024 15:56:39 UTC
2024/02/29 10:31:19 Fetching index for ubuntu 22.04 jammy-updates main component...
2024/02/29 10:31:20 Fetching index for ubuntu 22.04 jammy-updates universe component...
2024/02/29 10:31:20 Fetching pool/main/n/netbase/netbase_6.3_all.deb...
2024/02/29 10:31:20 Extracting files from package "netbase"...
$ ls foo/etc
./  ../  ethertypes  hosts  networks  protocols  rpc  services
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

### CODE REVIEW

**Review by zhijie-yang — APPROVED** [review]
Looks good to me.

**Comment by norrisjeremy** [comment]
@cjdcordeiro @rebornplusplus What's the hold-up on getting this merged? It's been languishing for over a month.

**Review by linostar — APPROVED** [review]
LGTM, thanks.

**Comment by cjdcordeiro** [comment]
> This is missing the copyright file. can you add it please?



> This is missing the copyright file. can you add it please?

Just did. Waiting for CI

**Review by cjdcordeiro — APPROVED** [review]
all good here as well. ty

**Pull request merged**
