### PR TITLE
fix(24.04): update slice versions and t64 support for year 2038 problem

### PR DESCRIPTION
**Pull request by linostar**
# Proposed changes
This was originally a fix for a liblttng-ust slice which dotnet-runtime-8.0 slice depends on. But with the introduction of more *t64 packages in noble source, other slices needed similar fixes because of similar changes upstream on their counterpart packages.

In the meantime, python and libnode had minor version bumps in noble, so it was addressed as well in this PR.

In summary, this PR:
- replace non-t64 slices by their t64 counterparts (e.g. libssl3 -> libssl3t64)
- replace [lib]python3.11* by their 3.12 counterparts while updating 3.12 paths accordingly
- replace libnode108 by libnode109
- replacing /lib/* paths in some of the slices by /usr/lib/* paths

### Forward porting
N/A

## Testing
Covered by CI.

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context
For context, the *t64 libraries are replacements for their counterparts in 64-bit systems in order to fix the [year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). According to the foundations team, t64 are going to replace their counterparts, so it should be safe to remove the affected non-t64 slices for chisel.

### CODE REVIEW

**Comment by HadrienPatte** [comment]
I looks like we can not have multiple slices managing the same paths (see CI error: `error: slices liblttng-ust-common1_libs and liblttng-ust-common1t64_libs conflict on /usr/lib/*-linux-*/liblttng-ust-common.so.*`). But we can not fully replace the `libssl3` slice with the `libssl3t64` one because some packages depend on both depending on architecture:
* [libssh-4](https://packages.ubuntu.com/noble/libssh-4)
* [libpython3.11-minimal](https://packages.ubuntu.com/noble/libpython3.11-minimal)

Both depend on [libssl3](https://packages.ubuntu.com/noble/libssl3) on `[amd64]` and [libssl3t64](https://packages.ubuntu.com/noble/libssl3t64) on `[not amd64]` and according to [this comment](https://github.com/canonical/chisel-releases/blob/20b1172b215f514c5512002f5df464bb0ae1724f/slices/libnode108.yaml#L6), chisel does not support per architecture dependencies.
> The chisel tool does not support per-architecture packages

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
Similar to what @rebornplusplus raised in https://github.com/canonical/chisel-releases/pull/214, these diffs need some justification, especially for the additional dependencies that are not listed upstream:

<details>
<summary>slices/libpython3.12-stdlib.yaml</summary>

```diff
@@ -5,11 +5,13 @@
 libffi8
 liblzma5
 libncursesw6
+libnsl2
 libpython3.12-minimal
 libreadline8t64
 libsqlite3-0
 libtinfo6
+libtirpc3t64
+libuuid1
 media-types
-mime-support
 netbase
 tzdata
```

---

Similarly for `python3.12.yaml`, why is `tzdata` removed?

Apart from that, it's looking good.

**Comment by linostar** [comment]
> Similar to what @rebornplusplus raised in #214, these diffs need some justification, especially for the additional dependencies that are not listed upstream:
> 
> > slices/libpython3.12-stdlib.yaml
> > ```diff
> > @@ -5,11 +5,13 @@
> >  libffi8
> >  liblzma5
> >  libncursesw6
> > +libnsl2
> >  libpython3.12-minimal
> >  libreadline8t64
> >  libsqlite3-0
> >  libtinfo6
> > +libtirpc3t64
> > +libuuid1
> >  media-types
> > -mime-support
> >  netbase
> >  tzdata
> > ```
> 
> Similarly for `python3.12.yaml`, why is `tzdata` removed?
> 
> Apart from that, it's looking good.

Oh I wasn't aware that the github-actions comment gets updated with each new commit. Noice!

I have now removed the 3 extra dependencies because they were carried over from 3.11 and they are no longer needed in 3.12.

As for tzdata, it is already indirectly included in `standard > libpython3.12-stdlib_data-types`.

**Review by cjdcordeiro — APPROVED** [review]
thanks for the changes.

lgtm

will wait for another +1 before merging (@rebornplusplus @zhijie-yang @letFunny )

**Pull request merged**
